stages:
 # - install-environment
  - build
  - baseline
  - cleanup


build-jiva:
   stage: build
   #image: harshvkarn/dind:v6
   before_script:
     - export COMMIT=${CI_COMMIT_SHA:0:8}
     - sudo apt-get install -y
     - sudo apt-get install -y curl open-iscsi
#     - mkdir -p $HOME/gopath/bin
#     - export GOPATH=$HOME/gopath/bin
     - export GOPATH=$HOME/go
     - export PATH=$HOME/go/bin:$PATH
     - mkdir -p $HOME/go/src/github.com/openebs/maya
     - rsync -az --delete ${CI_PROJECT_DIR}/ ${HOME}/go/src/github.com/openebs/jiva/ #CI_PROJECT_DIR is full path where project is cloned
     - go env
     - ls $GOPATH
     - cd ${HOME}/go/src/github.com/openebs/jiva
     - find . -name '*.php' -exec sed -i -e "s/ci/${COMMIT}/g" {} \;
     - go env
     - ls $GOPATH
   script: 
    - echo "Building-Jiva"
    - echo $COMMIT
    - pwd
    - ls
    - make build
    - ls

baseline-image:
  stage: baseline
  script:
     - pwd
     - export BRANCH=${CI_COMMIT_REF_NAME}
     - echo $BRANCH
     - export COMMIT=${CI_COMMIT_SHA:0:8}
     - echo $COMMIT
     - git clone https://github.com/openebs/e2e-infrastructure.git
     - ls
     - pwd
     - cd e2e-infrastructure/baseline
     - ls
     - pwd
     - ansible-playbook commit-writer.yml --extra-vars "branch=$BRANCH repo=$CI_PROJECT_NAME commit=$COMMIT"
     - ls
     - git status
     - git add baseline
     - git status
     - git commit -m "updated $CI_PROJECT_NAME commit:$COMMIT"
     - git push  https://$user:$pass@github.com/openebs/e2e-infrastructure.git --all

cleanup:
  stage: cleanup
  script:
     - pwd
     - ls
